app <- ShinyDriver$new("../")
app$snapshotInit("test")

app$setInputs(inNavbar = "1. Define Process")
app$setInputs(`stoich.high_1` = character(0))
app$setInputs(`stoich.high_1` = 2)
app$setInputs(`stoich.high_2` = character(0))
app$setInputs(`stoich.high_2` = 2)
app$setInputs(`stoich.high_3` = character(0))
app$setInputs(`stoich.high_3` = 2)
app$setInputs(inNavbar = "2. PMI Values")
app$setInputs(mw_A = 1)
app$setInputs(mw_A = 123)
app$setInputs(mw_B = 123)
app$setInputs(mw_C = 123)
app$setInputs(mw_D = 123)
app$setInputs(pmi_min_B = 2)
app$setInputs(pmi_min_B = 20)
app$setInputs(pmi_max_B = 5)
app$setInputs(pmi_max_B = 50)
app$setInputs(pmi_min_D = 2)
app$setInputs(pmi_min_D = 20)
app$setInputs(pmi_max_D = 5)
app$setInputs(pmi_max_D = 50)
app$setInputs(inNavbar = "3. Results")
app$setInputs(goButton = "click")
app$snapshot()
