app <- ShinyDriver$new("../")
app$snapshotInit("test", screenshot= FALSE)

app$setInputs(inNavbar = "1. Define Process")
app$setInputs(add = "click")
app$setInputs(InLabel4 = "D")
app$setInputs(OutLabel4 = "E")
app$setInputs(`stoich.high_2` = 2)
app$setInputs(`stoich.high_4` = 2)
Sys.sleep(0.5)
app$setInputs(inNavbar = "2. PMI Values")
Sys.sleep(0.5)
app$setInputs(mw_A = 123)
app$setInputs(mw_B = 123)
app$setInputs(mw_C = 123)
app$setInputs(mw_D = 123)
app$setInputs(mw_E = 123)
app$setInputs(pmi_min_B = 20); Sys.sleep(0.5)
app$setInputs(pmi_max_B = 50);Sys.sleep(0.5)
app$setInputs(pmi_min_D = 20);Sys.sleep(0.5)
app$setInputs(pmi_max_D = 50);Sys.sleep(0.5)
app$setInputs(pmi_min_E = 20);Sys.sleep(0.5)
app$setInputs(pmi_max_E = 50);Sys.sleep(0.5)
app$setInputs(conv_B = c(0.62, 0.95))
app$setInputs(conv_B = c(0.62, 0.99))
app$setInputs(conv_D = c(0.58, 0.95))
app$setInputs(conv_D = c(0.58, 0.78))
app$setInputs(conv_E = c(0.5, 0.91))
app$setInputs(conv_E = c(0.64, 0.91))
Sys.sleep(0.5)
app$setInputs(inNavbar = "3. Results")
Sys.sleep(0.5)
app$setInputs(N.iter = 100)
app$setInputs(goButton = "click")
Sys.sleep(0.5)
app$snapshot(list(output = "diagram"))
app$snapshotDownload("downloadData")
