app <- ShinyDriver$new("../")
app$snapshotInit("test")

app$setInputs(inNavbar = "1. Define Process")
app$setInputs(add = "click")
app$setInputs(InLabel4 = "D")
app$setInputs(OutLabel4 = "E")
app$setInputs(`stoich.high_2` = 2)
app$setInputs(`stoich.high_4` = 2)
app$setInputs(inNavbar = "2. PMI Values")
app$setInputs(mw_A = 123)
app$setInputs(mw_B = 123)
app$setInputs(mw_C = 123)
app$setInputs(mw_D = 123)
app$setInputs(mw_E = 123)
app$setInputs(pmi_min_B = 2)
app$setInputs(pmi_min_B = 20)
app$setInputs(pmi_max_B = 5)
app$setInputs(pmi_max_B = 50)
app$setInputs(pmi_min_D = 2)
app$setInputs(pmi_min_D = 20)
app$setInputs(pmi_max_D = 5)
app$setInputs(pmi_max_D = 50)
app$setInputs(pmi_min_E = 2)
app$setInputs(pmi_min_E = 20)
app$setInputs(pmi_max_E = 5)
app$setInputs(pmi_max_E = 50)
app$setInputs(conv_B = c(0.62, 0.95))
app$setInputs(conv_B = c(0.62, 0.99))
app$setInputs(conv_D = c(0.58, 0.95))
app$setInputs(conv_D = c(0.58, 0.78))
app$setInputs(conv_E = c(0.5, 0.91))
app$setInputs(conv_E = c(0.64, 0.91))
app$setInputs(inNavbar = "3. Results")
app$setInputs(goButton = "click")
app$snapshot(list(output = "tbl"))
